### ISSUE TITLE
Meaning of individual coefficients

### ISSUE THREAD

**Issue by wordsmith189** [bhmevik/pls#16]
Why is it that ``model$coefficients`` specifies coefficients for each predictor in each component? Are these different from the loadings? I understand that there would be coefficients for each _component_, but can't figure out how to interpret the different coefficients for each _predictor_ in each component.

**Comment by bhmevik** [comment]
A little over-simplified, it can be said that the loadings are the coefficients that transform the original predictor variables into the score values used in the regression part of the algorithm. That regression gives you a set of regression coefficients for predicting response values from the scores. The coefficients returned by `coef(mymod)` in the pls package is a combination of those coefficients, so that one can predict the responses directly from the original predictor variables. They are not as useful for interpretation as the loadings, and are mainly used for predicting response values for new data.

**Comment by wordsmith189** [comment]
This is very helpful. Thank you!

**Comment by czanetti** [comment]
Hello!
could someone kindly point me to the the line(s) of code where regression coefficients `(model$coefficients)` are generated in this package?

**Comment by khliland** [comment]
Hi Czanetti.

The coefficients are computed in the xx.fit functions, e.g., the default kernelpls.fit on line 156: https://github.com/khliland/pls/blob/caecf0a03f083ac9daf107eee50a4da6d597e507/R/kernelpls.fit.R#L156

Regards,
Kristian

**Comment by czanetti** [comment]
Thanks!
