### ISSUE TITLE
RMSEP suggesting zero components

### ISSUE THREAD

**Issue by johstu** [bhmevik/pls#25]
Hello!
I have a question regarding the validity of my model. It is set up as 1xPerformance ~ 200xConnectivityParameters (training-dataset 250 and test-dataset 50 participants). 
Performing the plsr including one component on the training-dataset and testing it on the test-dataset gives me a significant correlation (r: .33, p=.01) between measured and predicted values. 
However, according to the RMSEP the suggested number of components to keep in my model is zero (giving me the smallest prediction error). Can I still suggest the model with one component to be meaningful?

![image](https://user-images.githubusercontent.com/56960478/79217497-41391e80-7e4f-11ea-8df9-1cf08328fa99.png)

Thanks a lot! 
Johanna

**Comment by bhmevik** [comment]
Hm. Tricky question. Normally I would not suggest a model with 1 component is meaningful if the cross-validated RMSEP of 0 components is lower. The fact that the RMSEP increases with the number of components would normally indicate that you are only fitting "noise". How did you do the cross-validation? (LOO or k-fold?)

**Comment by johstu** [comment]
Hey, thanks for the answer! I used LOO. Its weird, because the loadings that I get using one component are actually picturing something that I expected from the data. Should I rather use k-fold? 
What about performing permutation testing: If it would be noise, it would probably be clustered inconsistently (with really different loadings and correlation values) each time I use a "new"/shuffled dataset. So If I repeat the calculation with n-times shuffling my training and test data-set this could give me something like confidence intervals. Is that a reasonable idea to validate the data?

**Comment by bhmevik** [comment]
LOO is typically somewhat more precise than k-fold, so stick to LOO. I just asked because the RMSEP estimate for 0 components is always calculated as the LOO estimate (because there is a nice, closed form expression for it) even if one requested k-fold CV. That way, the increased uncertainty of the k-fold estimates for >= 1 components might have given values larger than for 0 components even when a LOO estimate for it would have given a lower value.
Yes, a permutation testing like you describe would give you estimates of confidence intervals for the no-correlation case that you could use for testing the observed correlation.
