### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by rorynolan** [bhmevik/pls#27]
I find the documentation in `mvr.Rd` confusing. This is principally because the `...` documented is the `mvr?()` `...` but there are other `...` in there (e.g. in `plsr()`) which are not the same, so this is confusing. I have some ideas for how this should be documented and would be happy to submit a PR. Let me know if this is something that you are interested in.
Thank you for a great package.

**Comment by bhmevik** [comment]
I'd be happy to see a pull request for documentation improvements. I've always thought it is difficult to document arguments that are implemented by an underlying function, because the CRAN rule is that the `\usage` section has to match the function definition exactly.  See, e.g., https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Documenting-functions Long time ago, I believe there was an optional section `\synopsis` that one could use to list typical or alternative function calls, but that seems to be gone now.

**Comment by rorynolan** [comment]
My first idea would be to give `plsr` explicit arguments.

```
plsr = function(x, y, z) {
  # some stuff here customizing the arguments for input into mvr
  mvr(x = x, y = y, z = z)
}
```

Then it would be much easier to document. Of course this is a slight re-implementation of plsr
but I think it it worth it for the sake of improved documentation.

Are you open to converting the package to roxygen2?

**Comment by bhmevik** [comment]
Changing the arguments of the functions can have unexpected results, so such a change would have to be very carefully tested.
I've never used roxygen2, so I don't think I'd want to convert the package to that, at least not without testing it in another packages first.

**Comment by rorynolan** [comment]
Unfortunately I don't have time to do this any more.
I have started using the PLS functionality in the `recipes` package, which internally relies on `mixOmics` and I'm happy with it.
Thank you for your replies though and good luck with the package.
:-)
